### ISSUE TITLE
Add sample how to use the lapixdl with wandb

### ISSUE THREAD

**Issue by johnnv1** [lapix-ufsc/lapixdl#10]
Just a snippet of code to save the results from lapixdl in the [wandb](wandb.ai/)

**Comment by johnnv1** [comment]
Considering that you already have a `wandb` at your code scope, now we can just use something like this:

```python
selected_cats = ['A', 'B', 'C']
metrics = {k: v for k, v in eval_test.to_dict()['By Class'].items() if k in selected_cats}
wandb.log({'test_evaluation': metrics})
```

Where eval_test it's the results of the evaluate process, like:

```python
from lapixdl.evaluation.evaluate import evaluate_segmentation

...

eval_test = evaluate_segmentation(gt_masks, pred_masks, categories)
```

And if you want to just send to wandb the results of all categories, can just use:

```python
wandb.log({'test_evaluation':  eval_test.to_dict()['By Class']})
```

@Andrevmatias  i dunno if we put this code snippet in some local of the repo, what do you think?

**Comment by johnnv1** [comment]
If you want just log the average, i recommend something like this:

```python
avg = {f'average_{k}': v for k, v in eval_test.to_dict()['Average'].items()}
wandb.log({'test_evaluation': avg})
```
or if you want to use the `metrics_by_cat` that just apply a filter to the metrics
```python
import numpy as np

metrics_choice = ['IoU', 'F-Score']
metrics_average = {f'average_{m}': np.nanmean([v[m] for v in metrics_by_cat.values()]) for m in metrics_choice}
wandb.log({'test_evaluation': metrics_average})
```

**Comment by Andrevmatias** [comment]
I think we can add all these examples in a new section of the README.md file
