### ISSUE TITLE
Division by zero at calculate_bbox_iou

### ISSUE THREAD

**Issue by johnnv1** [lapix-ufsc/lapixdl#21]
I can't reproduce the error with tests, but, some moments at https://github.com/lapix-ufsc/lapixdl/blob/ee3faf20b2beab7bbb794328f724b7b8044ac1b1/lapixdl/evaluation/evaluate.py#L211

The union it's equals zero and raise the error. To solve just need:
```python
if union_area == 0:
    return 0
```

I don't PR this because I can't reproduce this when i try

**Comment by Andrevmatias** [comment]
I think the only way to get an union area of 0 is to have 2 bboxes with 0 area or one of them having a negative area, what mostly indicates a problem with the bboxes that were passed to this method. Maybe the solution would be to put an assertion at the bbox constructor to make sure the values are valid.
